import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const encode=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const periodModule=encode(ts.transpile(fs.readFileSync('app/periods.ts','utf8'),{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}));
const historyModule=encode(ts.transpile(fs.readFileSync('app/taskHistory.ts','utf8'),{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}));
const targetModule=encode(ts.transpile(fs.readFileSync('app/targets.ts','utf8'),{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}).replace("'./periods'",JSON.stringify(periodModule)).replace("'./taskHistory'",JSON.stringify(historyModule)));
const {achievement,targetResults,overallScore}=await import(targetModule);
const {getPeriod,inPeriod,periodIndex}=await import(periodModule);
assert.equal(achievement(8,10),80);
assert.equal(achievement(12,10),120);
assert.equal(achievement(0,0),null);
const report={date:'2026-09-20',members:[{name:'Cindy',tasks:[{kategori:'Naskah Instagram',progress:'100'},{kategori:'Naskah Instagram',progress:'50'},{kategori:'Request',progress:'100'}]}]};
report.members[0].tasks.forEach((t,i)=>t.id=String(i));
let results=targetResults('Cindy',[report],0);
assert.equal(results.find(t=>t.title==='Total naskah konten Instagram grafis').target,22);
assert.equal(results.find(t=>t.title==='Total naskah konten Instagram grafis').actual,1);
assert.equal(targetResults('Cindy',[report],1)[0].actual,0);
assert.equal(targetResults('Mario',[],0)[0].score,null);
console.log('PASS: 80% example, zero target, category mapping, done only, month isolation, missing metric');
const metrics=[{date:'2026-09-16',members:[{name:'Dewi',metric:'100',tasks:[]},{name:'Mario',metric:'1000',tasks:[]},{name:'Ilham',metric:'10',tasks:[]}]},{date:'2026-09-20',members:[{name:'Dewi',metric:'1600',tasks:[]},{name:'Mario',metric:'80000',tasks:[]},{name:'Ilham',metric:'160',tasks:[]}]}];
assert.equal(targetResults('Dewi',metrics,0)[0].actual,1600);
assert.equal(targetResults('Dewi',metrics,0)[0].score,80);
assert.equal(targetResults('Mario',metrics,0)[0].actual,1600);
assert.equal(targetResults('Mario',metrics,0)[1].score,80);
assert.equal(targetResults('Ilham',metrics,0).find(t=>t.title==='Total lead yang dihasilkan').score,80);

assert.equal(overallScore(targetResults('Mario',metrics,0)),80);
console.log('PASS: latest cumulative metrics, shared followers, likes, leads, normalized mixed-unit score');

assert.equal(getPeriod(0).start,'2026-09-15');
assert.equal(getPeriod(0).end,'2026-10-12');
assert.equal(getPeriod(1).start,'2026-10-13');
assert.equal(getPeriod(1).end,'2026-11-09');
assert.equal(inPeriod('2026-09-14',0),false);
assert.equal(inPeriod('2026-09-15',0),true);
assert.equal(inPeriod('2026-10-12',0),true);
assert.equal(inPeriod('2026-10-13',0),false);
assert.equal(periodIndex('2026-10-13'),1);
const crossMonth=[{...report,date:'2026-10-12'}];
assert.equal(targetResults('Cindy',crossMonth,0)[0].actual,1);
assert.equal(targetResults('Cindy',crossMonth,1)[0].actual,0);
assert.equal(targetResults('Dewi',metrics,1)[0].actual,null);
console.log('PASS: 28-day boundaries, cross-month activity, cumulative reset and next period');
assert.equal(periodIndex('2026-09-08'),-1);
assert.equal(getPeriod(-1).start,'2026-08-18');
assert.equal(getPeriod(-1).end,'2026-09-14');
assert.equal(inPeriod('2026-09-14',-1),true);
assert.equal(inPeriod('2026-09-15',-1),false);
assert.equal(periodIndex('2026-09-15'),0);
console.log('PASS: current period before first period and September 15 rollover');
const alinReport={date:'2026-09-10',members:[{name:'Alin',tasks:[...Array.from({length:4},()=>({kategori:'Desain Request',progress:'100'})),{kategori:'Desain Request',progress:'50'}]}]};
alinReport.members[0].tasks.forEach((t,i)=>t.id=String(i));
const alinTargets=targetResults('Alin',[alinReport],-1);
assert.equal(alinTargets.find(t=>t.title==='Desain Request').actual,4);
assert.equal(alinTargets.find(t=>t.title==='Desain Request').target,30);
assert.equal(overallScore(alinTargets),11);
assert.equal(alinTargets.some(t=>t.title==='Total konten grafis'),false);
assert.equal(targetResults('Zakki',[],0).find(t=>t.title==='Total desain grafis').target,22);
console.log('PASS: Alin completed requests count toward 30 target and score; Zakki unchanged');

const {prepareDay,taskHistory}=await import(historyModule);
const blank={hasProblem:false,problem:'',solution:'',status:'Belum solved'};
const sample=(date,progress)=>({id:date,date,division:'marketing',problem:blank,members:[{name:'Amar',metric:'',...blank,tasks:[{id:'ad-1',pekerjaan:'Iklan A',kategori:'Video Iklan',progress}]}]});
const wednesday=sample('2026-09-09','50');
const thursday=prepareDay([wednesday],'marketing','2026-09-10',['Amar']);
assert.equal(thursday.members[0].tasks[0].progress,'50');
assert.equal(thursday.members[0].tasks[0].id,'ad-1');
assert.equal(prepareDay([wednesday],'marketing','2026-09-15',['Amar']).members[0].tasks.length,1);
assert.equal(prepareDay([wednesday],'sosmed','2026-09-10',['Cindy']).members[0].tasks.length,0);
assert.equal(prepareDay([wednesday],'marketing','2026-09-08',['Amar']).members[0].tasks.length,0);
const unchanged=sample('2026-09-10','50');
assert.equal(targetResults('Amar',[wednesday,unchanged],-1)[0].actual,0);
const complete=sample('2026-09-11','100');
const duplicate=sample('2026-09-12','100');
assert.equal(targetResults('Amar',[wednesday,unchanged,complete,duplicate],-1)[0].actual,1);
assert.equal(prepareDay([wednesday,unchanged,complete],'marketing','2026-09-12',['Amar']).members[0].tasks.length,0);
assert.equal(prepareDay([wednesday,complete],'marketing','2026-09-10',['Amar']).members[0].tasks[0].progress,'50');
const edit=prepareDay([wednesday],'marketing','2026-09-09',['Amar']);edit.members[0].tasks[0].progress='80';assert.equal(wednesday.members[0].tasks[0].progress,'50');
const nextPeriod=sample('2026-09-15','100');
assert.equal(targetResults('Amar',[wednesday,nextPeriod],-1)[0].actual,0);
assert.equal(targetResults('Amar',[wednesday,nextPeriod],0)[0].actual,1);
assert.equal(targetResults('Amar',[wednesday,complete,nextPeriod],0)[0].actual,0);
assert.equal(taskHistory([wednesday,unchanged,complete]).length,1);
console.log('PASS: carry-forward 50%, skipped dates, historical edits, completion once, period boundaries and immutable snapshots');
