import {useState} from 'react';
import {inPeriod,getPeriod} from './periods';
import {taskHistory} from './taskHistory';
import {targetResults,overallScore} from './targets';
import {categories,SavedReport,Task} from './reportData';

const shortTitles:Record<string,string>={
 'Total desain grafis':'Grafis Instagram','Total desain thumbnail IG':'Thumbnail','Total naskah konten Instagram grafis':'Naskah Instagram','Total naskah konten Instagram reels':'Naskah Reels','Total naskah konten TikTok':'Naskah TikTok','Total video Instagram':'Video Instagram','Total video TikTok':'Video TikTok','Total naskah iklan':'Naskah iklan','Total naskah YouTube':'Naskah YouTube','Total thumbnail YouTube':'Thumbnail YouTube','Total konten iklan':'Video iklan','Total konten YouTube':'Video YouTube','Total konten grafis':'Desain grafis','Total pertumbuhan followers':'Followers','Total penambahan likes TikTok':'Likes TikTok','Total lead yang dihasilkan':'Lead','Jumlah ide kreatif team (campaign)':'Ide campaign','Jumlah konten dealdone':'Konten dealdone','Jumlah campaign yang dieksekusi':'Campaign','Ide visual konten baru':'Ide visual','Ide konten baru':'Ide konten','Ide marketing baru':'Ide marketing'
};
type EditHandler=(report:SavedReport,member:string,taskId:string,patch:Pick<Task,'pekerjaan'|'kategori'|'progress'>)=>Promise<void>;
export default function MemberReportPanels({names,reports,scoreReports,period,onEdit,busy}:{names:string[];reports:SavedReport[];scoreReports:SavedReport[];period:number;onEdit:EditHandler;busy:boolean}){
 return <div className="member-report-panels">{names.map(name=>{
 const targets=targetResults(name,scoreReports,period);
 const score=overallScore(targets);
 const entries=reports.flatMap(r=>r.members.filter(m=>m.name===name).map(m=>({...m,date:r.date,report:r}))).sort((a,b)=>b.date.localeCompare(a.date));
 const monthlyTasks=taskHistory(scoreReports,getPeriod(period).end).filter(t=>t.member===name&&inPeriod(t.date,period));
 const requests=Array.from(new Set([...(categories[name]||[]),...monthlyTasks.map(t=>t.kategori)])).filter(label=>/request/i.test(label)&&!targets.some(t=>t.title.trim().toLowerCase()===label.trim().toLowerCase()));
 const summaries=[...targets.map(t=>({label:shortTitles[t.title]||t.title,value:`${t.actual===null?'—':t.actual.toLocaleString('id-ID')} / ${t.target.toLocaleString('id-ID')}`,title:`${t.title}: hasil / target 28 hari`})),...requests.map(label=>({label,value:`${monthlyTasks.filter(t=>t.kategori===label&&Number(t.progress)===100&&t.completedOn!==null&&inPeriod(t.completedOn,period)).length} / ${monthlyTasks.filter(t=>t.kategori===label).length}`,title:'Request: selesai / jumlah request dilaporkan; tidak termasuk skor target'}))];
 return <section className="member-report-panel" key={name}><header className="member-panel-heading"><h3>{name}</h3><span>Skor <strong>{score===null?'—':`${score}%`}</strong></span></header><div className="member-inner-section"><h4>Target</h4><div className="member-target-strip" aria-label={`Target ${name}`}>{summaries.map(s=><div className="member-target-item" key={s.label} title={s.title}><span>{s.label}</span><strong>{s.value}</strong></div>)}</div></div><div className="member-inner-section"><h4>Aktivitas</h4><div className="member-activities-scroll"><table className="member-activities-table"><caption className="sr-only">Aktivitas harian {name} dari report leader</caption><thead><tr><th scope="col">Aktivitas</th><th scope="col">Kategori</th><th scope="col">Progress</th></tr></thead><tbody>{entries.length?entries.map(entry=><DayRows key={entry.date} entry={entry} onEdit={onEdit} busy={busy}/>):<tr><td colSpan={3} className="member-empty">Belum ada aktivitas dari report leader pada periode ini.</td></tr>}</tbody></table></div></div></section>;
 })}</div>;
}
function DayRows({entry,onEdit,busy}:{entry:SavedReport['members'][number]&{date:string;report:SavedReport};onEdit:EditHandler;busy:boolean}){
 return <><tr className="activity-date"><th colSpan={3} scope="rowgroup">{new Date(entry.date+'T12:00:00').toLocaleDateString('id-ID',{dateStyle:'long'})}</th></tr>{entry.tasks.length?entry.tasks.map(t=><EditableActivity key={t.id} task={t} member={entry.name} report={entry.report} onEdit={onEdit} busy={busy}/>):<tr><td colSpan={3} className="member-empty">Tidak ada aktivitas dilaporkan.</td></tr>}</>;
}
function EditableActivity({task,member,report,onEdit,busy}:{task:Task;member:string;report:SavedReport;onEdit:EditHandler;busy:boolean}){
 const [draft,setDraft]=useState<Task|null>(null),[original,setOriginal]=useState(report),[error,setError]=useState(''),[pending,setPending]=useState(false);
 async function save(){if(!draft)return;setPending(true);setError('');try{await onEdit(original,member,task.id,draft);setDraft(null);}catch(e){setError((e as Error).message);}finally{setPending(false);}}
 return <tr>{draft?<><td><textarea aria-label={`Edit aktivitas ${member}`} value={draft.pekerjaan} disabled={pending} onChange={e=>setDraft({...draft,pekerjaan:e.target.value})}/>{error&&<p role="alert" className="edit-error">{error}</p>}</td><td><input aria-label={`Edit kategori ${member}`} value={draft.kategori} disabled={pending} onChange={e=>setDraft({...draft,kategori:e.target.value})}/></td><td><input aria-label={`Edit progress ${member}`} type="number" min="0" max="100" step="any" value={draft.progress} disabled={pending} onChange={e=>setDraft({...draft,progress:e.target.value})}/><div className="activity-edit-actions"><button type="button" className="save-activity" disabled={busy||pending} onClick={()=>void save()}>{pending?'Menyimpan…':'Simpan'}</button><button type="button" disabled={pending} onClick={()=>{setDraft(null);setError('');}}>Batal</button></div></td></>:<><td>{task.pekerjaan}</td><td>{task.kategori}</td><td><div className="activity-edit-display"><span className={Number(task.progress)===100?'activity-done':'activity-progress'}>{task.progress}%{Number(task.progress)===100?' · Done':''}</span><button type="button" className="edit-activity" aria-label={`Edit ${task.pekerjaan} — ${member}`} disabled={busy} onClick={()=>{setOriginal(report);setDraft({...task});setError('');}}>Edit</button></div></td></>}</tr>;
}
